### ISSUE TITLE
Cosys Integration

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#102]
CoSys is a platform for generating PDF documents from the process context. I.e. the contents of a document and the ID of the template come from the process. With this CoSys generates the PDF and returns it. This PDF can then be handled further in the process (e.g. sent by mail, placed in a DMS, etc.).

This Epic includes:
- Solve the Cosys integration from the monolith.
- Create Spring Boot Starter for the Cosys functionality
- Include S3 as a (temporary) file store
- create a sample project for a Cosys integration artifact

**Comment by dominikhorn93** [comment]
![Bildschirmfoto 2022-04-08 um 13.17.05.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/e8b047d3-afff-416b-8ff6-471e90aab567)
