### ISSUE TITLE
Kafka topic documentation and topic concept

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#105]
DigiWF engine listens to multiple kafka topics for events that are processed. Internally the digiWF engine routes incoming (kafka) events to the appropriate consumers based on the message header `type`. This approach makes it difficult to decide whether to use an already existing topic or to create a new one.

To simplify this we should provide detailed documentation on existing kafka topics and their usage as well as documentation for creating new topics.

**Tasks**

* Document existing kafka topics and their usage
* Naming conventions for kafka topics
* Instructions and tutorials on how to communicate with digiWF engine using a new kafka topic

**Comment by xdoo** [comment]
Please use digiwf.muenchendigital.io -> digiwf-project
