### ISSUE TITLE
Generic error handling

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#107]
## Description
The digiwf engine communicates with integration artifacts via asynchronous events sent through Kafka. If an error appears during event processing in the integration artifact, an error event is sent to a configured dead letter queue (dlq). At the moment the errors in the dlq topic are not handled. This behaviour is not ideal, as errors are not detected.
To improve the error handling of async events we should listen to error events sent to the dlq and handle them properly in digiWF engine.

Estimation: 20 Days

#### Digiwf-integration-errors topics
Request a digiwf-integration-errors topic that can be used as a dlq for integration artefacts.
Authorize kafka users for the topic

#### DTO for creating incidents
For creating incidents it is necessary to know in which context the incident should be created.
The Incident should be created on the receive task / message event in the bpmn process.
to be more precise, in the corresponding job of the message. To query for the message we need the same parameters as we need for correlating. For the first version we can restrict it to:
- messageName: string
- processInstanceId: string
- errorMessage: string

#### spring cloud stream Incident handler
Create a handler for the header type `createIncident`
The should query for the corresponding exectuion with ` this.runtimeService.createEventSubscriptionQuery()` and use ` this.runtimeService.createIncident()` for creating an incident.

#### DTO for creating bpmn error
For creating incidents we it is necessary to know in which context the bpmn error should be created.
- processInstanceId: string
- errorCode: string
- errorMessage: string

#### spring cloud stream bpmn error handler 
Create a handler for the header type `createBpmnError`
**Check alternatives for correlating messages**
Correlate the message with the parameters that determine that it is a bpmn error
- errorCode: string
- errorMessage: string

#### enable bpmn errors by input variable
Only throw bpmn errors if the variable app_bpmn_erorrs_enabled is activated (true)

#### create example process
Create an example process for incidents and bpmn errors

#### extend spring cloud stream utils 
Extend the spring cloud stream utils for throwing bpmn errors and creating incidents

**Comment by dominikhorn93** [comment]
![image.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/15d1cf1b-1045-48de-b638-6d6e1e4ba995)

**Comment by dominikhorn93** [comment]
![image.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/1fe6a86b-3f2d-411b-b09f-e03d03dfa05d)

**Comment by dominikhorn93** [comment]
@lmoesle I have added 2 slides in that presentation (Connector section) One is about the package structure and one about a sample mail use case. https://docs.google.com/presentation/d/1ReihB4kIMPViTVJgL91b2mfxGhZccRWbTKBjdQNF1sM/edit

I will merge the current state of DigiWF-core into dev. Is nothing for production usage an of course still in beta. But you have to create new branches next week.
