### ISSUE TITLE
Professional extension of the task list

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#111]
The task list is currently designed for a very rudimentary processing of user tasks. Increasingly, however, more complex functionalities are required. These are for example:

- different inboxes
- assignment of tasks by a superuser
- dashboards
- clerk workstation
- ...

In DigiWF the 80:20 rule applies. I.e. we try to map 80% of the functionality that everyone needs. If you have extra wishes, you have to implement them yourself. This also applies to the Tasklist. Not all requirements have to be implemented, but the user must have the possibility to build his own application from the interface components of the DigiWF Tasklist. 

Within the scope of this epic, all known requirements from the implementation projects shall be collected. Based on the result, a user interface concept based on VueJs / VuetifyJs shall be created following the material design rules (!!!). These components (also the frame can be a component) will then be built into the current tasklist. It is also legitimate requirements not to implement. This should be documented in the context of this epic.

**Comment by dominikhorn93** [comment]
@xdoo  Splitted in multiple Epics - to big for one
