### ISSUE TITLE
Provide the DigiWF Tasklist Open Source

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#125]
Is your feature request related to a problem? Please describe.
The DigiWF Tasklist cannot be used or developed open source at the moment

Describe the solution you'd like
The DigiWF task list should become part of the DigiWF core monorepos and be developed open source

Additional context

Separate DigiWF Tasklist from Spring Cloud Gateway
Create pipeline for Docker
Clarify whether own form components are included
Concept to extend task list with own fields

**Comment by xdoo** [comment]
@a-m-zill

**Comment by xdoo** [comment]
@dominikhorn93 what is the actual state here?

**Comment by dominikhorn93** [comment]
@xdoo frontend code is open source 👍 
We can close this issue
