### ISSUE TITLE
Create Consumer for BPMN Errors

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#149]
## Description

We need a consumer that listens to BPMN errors and correlates the bpmnError Message in the specific StreamingTemplate process instance. 

## Details
Request a digiwf-integration-errors topic
- A new event type `createBpmnError`should be created and added to the typeMappings
- Create the BpmnErrorEventDto
  - processInstanceId: string
  - errorCode: string
  - errorMessage: string
- Correlate the bpmnError Message for the specific processInstanceId and pass the errorCode and errorMessage
- Log.error if a bpmn error cannot be correlated do not create a dlq of bpmn errors

## Technical hints
- create a new `errors` package in the digiwf-connector-core module. You can copy the message package. It will be almost the same
- create a ErrorService Interface that is implemented in digiwf-camunda-connector module. You can almost copy everything from the MessageServiceImpl because we will implement BPMN Errors via a EventSubprocess that is correlated with a message
- extends the *-rest module to easily test the whole setup without the need of a sample integrations service that throws errors. You can copy the message package

**Comment by dominikhorn93** [comment]
I would use *-errors for BPMN errors and *-incidents for Incidents

**Comment by dominikhorn93** [comment]
Hi @lmoesle we talked about a sample integration service that can be used. I would do that in a second step. First step would be extending the rest api to fake it. Can be done more easily. I have created some technical hints for that issue

**Comment by martind260** [comment]
Topics are commissioned (https://git.muenchen.de/openshift/kafka/-/issues/70)
