### ISSUE TITLE
Document Error-Handling Concept

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#150]
## Description

We need the documentation for two different types of stakeholders.
- Integration services developers
- Process engineers

- We need to describe how to send bpmn errors / incidents manually
- We need to describe how to configure DLQ Handling to automatically create incidents after the number of attempts trying to complete a message fail

**Comment by xdoo** [comment]
Please use digiwf.muenchendigital.io -> digiwf-project for this
