### ISSUE TITLE
Add functionality for updating artifacts via repository-ui

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#156]
**Is your feature request related to a problem? Please describe.**
There is no possibility to update artifacts via an upload

**Describe the solution you'd like**
Create the possibility to update the latest milestone of an artifact via an upload

**Additional context**
- adjust backend
- adjust frontend (add entry in drop down)

**Comment by lmoesle** [comment]
If there is no editor for the artifact type, an upload dialog is displayed. In this dialog the user can upload the most recent version of the artifact.

@dominikhorn93 do we need upload dialogs for all artifact types? Is it sufficient to only show this upload dialog for unsupported artifact types (everything that is not bpmn, dmn or form)?
