### ISSUE TITLE
Create a .editorconfig 

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#17]
**Is your feature request related to a problem? Please describe.**
We don't have an editorconfig at the moment. That's why indentations and quotation marks have different characteristics

**Describe the solution you'd like**
We should have an editorconfig that we use in every project.

**Comment by darenegade** [comment]
@dominikhorn93 we can use this one (Had to change the filename in order to upload it here):

[https://app.zenhub.com/files/459665365/c9080f6c-27bd-440b-9710-13677bd861e2/download](https://app.zenhub.com/files/459665365/c9080f6c-27bd-440b-9710-13677bd861e2/download)

**Comment by darenegade** [comment]
Wird abgelöst von: https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/345
