### ISSUE TITLE
Create and configure github Repository

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#207]
## TODO
- Create Repository on github (use https://github.com/it-at-m/oss-repository-en-template): e.g. digiwf-oce-cosmos-integration
- Cleanse and update README.md

##  Criteria
- We have a repository with a traceable readme.md file.

**Comment by darenegade** [comment]
https://github.com/it-at-m/digiwf-oce-cosmos-integration

**Comment by darenegade** [comment]
Readme & Doc init done
