### ISSUE TITLE
Create base Java structure

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#208]
## TODO
- Create a Spring Boot project
- Add all necessary dependencies for a basic integration artifact (e.g. Spring Cloud Stream, Stream Utils, ...)

## Criteria
We have a runnable Spring Boot project.

**Comment by darenegade** [comment]
https://github.com/it-at-m/digiwf-oce-cosmos-integration/commit/15b92b95bd563485cd8073650476295828aa690f
