### ISSUE TITLE
[feature] Create changelog

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#215]
**Is your feature request related to a problem? Please describe.**
The Changelog contains all changes of a specific version of an artefact and supports i.a. Operational Management when maintaining the Operations Manual. Currently it is difficult to see what changes have been made to an artifact.

**Describe the solution you'd like**
All changes worth mentioning are added to the CHANGELOG. The maintenance is done manually, not via the autom. readout of commit messages. It is mandatory in the sense of the Definition of Done.
The format should look like this (according to Github):
```
# Change Log
All notable changes to this project will be documented in this file.

## [Unreleased] - yyyy-mm-dd
### Added
- Feature process and element template for Email integration

### Changed
- Rewrite documentation about authorization

### Fixed
- Info display missing

## [1.0.0] - 2022-01-12
### Added
- New form field "preview"

### Changed
- ...

### Fixed
- ...
```
When building a release, the "Unreleased" line is autom. replaced by the release version with date and a new "Unreleased" area is inserted.

**Describe alternatives you've considered**

**Additional context**

** Acceptance criteria **
- [ ] Format von Changelog angepasst
- [ ] In zentrale Doku Features -> Änderungen umgezogen

**Comment by darenegade** [comment]
We are going a diffrent way with change communication
