### ISSUE TITLE
Feedback about contributing section in README

### ISSUE THREAD

**Issue by darkdragon-001** [it-at-m/digiwf-project#22]
Normal users on Github can't easily add tags to their issues. Instead of a complicated description in the README, it is advisable to create [_issue templates_](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) which lead the user to create issues in the desired format (if desired which also a bot can understand to apply labels automatically).

**Comment by xdoo** [comment]
Good idea. I added two templates for bug and issues.

**Comment by darkdragon-001** [comment]
See #23
