### ISSUE TITLE
As a developer I want to have a blueprint how to develop an deploy a new integration artefact

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#222]
**Is your feature request related to a problem? Please describe.**
Currently, it is not clear when we create a Docker image from an integration repository and when we do not. Even if the decision is made to create a Docker image and deploy it to Dockerhub, there is no consistent pattern on how to manage the configurations. 

**Describe the solution you'd like**
The goal is to create a blueprint that addresses the following questions:
- When does it make sense to make an integration artifact available not only as a Spring Boot Starter on Maven Central, but also as a finished Docker image on Dockerhub?
- How are the configurations (e.g., currently held in different application.yml files) passed to the system?
- How can configurations that occur repeatedly be managed effectively?
- How to provide Elemente Template?
- Hot to provide Sample Processes`?

**Comment by xdoo** [comment]
@martind260

**Comment by darenegade** [comment]
https://digiwf.oss.muenchen.de/integrations/
