### ISSUE TITLE
As a user I want to authenticate via sso in the new tasklist backend

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#242]
## Description
For the new task management backend we decided to use Taskana. The Spring Security of the Taskana launcher should be adapted to work with the SSO server of the LHM. Authentication via LDAP directly is not an option. The groups of the user have to be mapped accordingly, so that they can be used for the authorization in Taskana.

#### Customize security config
The security config should be adjusted so that it checks against oAuth2. It can be based on the RefArch

#### Customize filter bean
the filter bean should be adapted so that the corresponding security principles are loaded from the token information and the group information from the LDAP. These have to be included in the subject of JaasAuthentication, because Taskana needs them.

**Comment by darenegade** [comment]
We don't use Taskana and the new Task-Service already authenticates against SSO.
