### ISSUE TITLE
As a user I want to have api acess to task I am assigned to

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#243]
## Description
For the implementation of the new task management we rely on Taskana.
Here we need the possibility to set user tasks.

Initially, only user tasks that are provided with a corresponding flag are to be set.
This flag should be configurable as an input variable in the UserTask.

The synchronization of the user task should be configured via a TaskListener, which in turn generates a corresponding event in Kafka.
This Kafka event is consumed by the Taskana TaskService and a corresponding task is created.

In the first step, only the assignee and the name of the task are to be transferred.

#### User task flag
Check if a user task has the flag app_task_service_export set to true.

#### Kafka Event
Define the CreateTask event that has the following properties:
- ID
- Name
- Assignee

Send the event to the corresponding topic with spring cloud stream functions

#### Create the task
Consume the kafka event and create the corresponding task

**Comment by darenegade** [comment]
Part of #489
