### ISSUE TITLE
As a user I want to have access to the task data in the new task service

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#244]
## Description
In DigiWF we define data structures and forms with json schema. 
The same json schema is used to give a user access to certain data in a task.
When we set tasks in Taskana, the data should be loaded and passed to Taskana using the stored Json schema.
For this purpose, the listener that generates the task events should be customized.

Do also pass common task variables as custom fields:
- task description (app_task_description)
- due date
- follow up date

#### Extend the task create event
- Load the corresponding json schema by the schema key that is available app_task_form_schema_key
- Load the data using the keys in the json schema ( HumTaskDataService)
- Extends the Event and add the data in the variables section

#### Process the task create event
Customize functionality when consuming the task event and save the variables

**Comment by dominikhorn93** [comment]
engine backend should be Open Source before implementing this feature

**Comment by darenegade** [comment]
Part of #489
