### ISSUE TITLE
As an operational process participant, I would like to see an overview of distributed tasks in inboxes in a dashboard for which I am responsible

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#246]
## Description
If multiple task lists are used, the distribution across them becomes confusing.
For monitoring and optimization purposes, it should be possible to monitor the distribution of tasks.

The issue of data protection should be taken into account here, and the department should explicitly request that individual inboxes be enabled.
Due to monitoring, general activation is probably not possible here.

#### Dashboard KPIs
- Amount of Tasks for each inbox
- Oldest Task for each inbox
- Number of users

#### Dashboard Authorization
For some KPIs Users that have access to a inbox have all information to viusalize the KPIs.
KPIs like "Number users" are more critical to data protection and only inbox admin users have access to that data.

**Comment by dominikhorn93** [comment]
@xdoo need to go in detail with the KPIs that should be on a dashboard

**Comment by darenegade** [comment]
First things first it-at-m/digiwf-core#976
