### ISSUE TITLE
Switch from RestTemplate to WebClient

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-project#258]
Currently, nearly all integrations artefacts and services are using the Spring RestTemplate to do rest requests to other services.

The `RestTemplate` will be deprecated in Future Spring-Versions. This class will then be replaced by `WebClient`

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html

![image](https://user-images.githubusercontent.com/56300801/174823863-889c663c-1033-453a-8ab2-4740ee167685.png)

Code generated with Swagger can use the library option `webclient` instead of `resttemplate`.

https://openapi-generator.tech/docs/generators/java/

![image](https://user-images.githubusercontent.com/56300801/174824982-d9e93eb0-65f5-4a7c-80b1-f7bbaa223217.png)

Known affected repos:

https://github.com/it-at-m/digiwf-s3-integration
https://github.com/it-at-m/digiwf-ok.verkehr-integration
https://github.com/it-at-m/digiwf-ok.ewo-integration
https://github.com/it-at-m/digiwf-s3-integration
https://github.com/it-at-m/digiwf-email-integration

**Comment by darenegade** [comment]
@dominikhorn93 FYI
