### ISSUE TITLE
Project specific S3 storages

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-project#260]
## Handling

Handling of files over S3 storages is currently restricted to the DigiWF specific storage. Its not possible to handle files in project specific storages.

Within a project specific process, it should be possible to handle files with project specific S3 storages.

## Authentication/authorization

All project specific S3 storages expose REST endpoints which will be secured with project specific ROLEs/RIGHTs using Oauth2.

I.e. the call to project specific S3 storages in the Cosys/Mail integration will be handled by Oauth2 client credentials flow. For each call to a project-specific S3 storage, the corresponding ClientID and the corresponding ClientSecret are then required in the Cosys/Mail integration.

Currently, this cannot be handled in the Cosys and Mail services. As a result the current images cannot be used for this purpose.

## Concept

![projektspezifischer-s3.png](https://images.zenhubusercontent.com/622f4d4cf7a5f47ea3c5213c/9771b0ea-3451-4b86-8b41-e9dbfb47bd84)

- Every process can use a specific S3 service (the s3 service is configured in the process config)
- Every S3 service has its own kafka topic (developers of the S3 service are responsible to claim the topic)

### DigiWF Engine
- Save process config as isntance variable when starting a process
  - adjust processConfigFunction bean to use variable as default and load from db as fallback
- Adjust Task Listener to extract specific s3 from process config and add it as input parameter
- Adjust Rest-Template to add Token by default
- Adjust TaskFileService to use specific S3 URL
- Adjust ProcessDefintionStart Service to use specific S3 URL

### S3 Service
- Add async interface for creating presigned urls
- Provide element templates for creating presigned urls

### Mail Service
- Adjust async interface to expect a list of presigned urls for loading documents
- adjust element template and add own template process

![image.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/9bdd3155-e6c8-4b4d-b7db-e1e3573aaeb6)

### Cosys Service
- Adjust async interface to expect a presigned url for saving documents
- adjust element template and add own template process

**Comment by boal** [comment]
Solution 1:

Possibly the Cosys/Mail integrations simply gets a global authorization to access all project-specific S3 storages.

Disadvantage: Here, via the central Cosys/Mail integration, each project can also store files in another S3 storage as soon as the URL of the S3 service is known.

**Comment by boal** [comment]
Solution 2:

The credentials for an project-specific access are stored within the process and the credentials are passed as attributes when the Mail/Cosys integration is called via the ElementTemplate.

The Mail/Cosys integration is then using the credentials to make a rest request to the project specific S3 storage.

Advantage: Another process/project can not access the project-specific S3 storage.

Disadvantage: The credentials are withn the process and are transferred via Kafka.

Translated with www.DeepL.com/Translator (free version)

**Comment by dominikhorn93** [comment]
@boal What about passing the presigned URLs to the integration services instead of a s3 path? 
Each S3 Service would need an async interface... Also, async could cause difficulties when the URLs expire.
But I think we should discuss this anyway.

**Comment by boal** [comment]
Yes, this is a third valid solution.

**Comment by boal** [comment]
1. Projektspezifische S3-Service benötigt asynchorne Schnittstelen analog zur synchrone Schnittstelle (eigenes projektstpezifisches S3-Topic) -> Basisbausteine,Elementtemplates
2. Synchon/Asynchron neue Schnittstelle für Listen an PresignedURL zum Laden von Dateien.
3. Integration wie Mail/Cosys erwarten die PresignedURL.
4. DigiWF core services bekommen Berechtigung für einen synchonen Zugriff auf den projektspezifischen S3-Service.

**Comment by boal** [comment]
@dominikhorn93

Which services are still affected?

**Comment by lmoesle** [comment]
Topics claimed: https://git.muenchen.de/openshift/kafka/-/issues/83

Todo: We need Topics for prod before we can relase the new feature

**Comment by lmoesle** [comment]
![project-specific-s3.PNG](https://images.zenhubusercontent.com/622f4d4cf7a5f47ea3c5213c/8a3cc8cf-2222-4bb4-baae-b138630019c7)

## What's working

- determine s3 storage by adding a process config. Each processdefinition can use a different s3 storage.
- create presigned urls for any s3 storage
- send emails with files attached from presigned urls
- multifile input can use any s3 storage

## What's still missing

- S3 storage authentication
- Cosys Integration
- Multifile Input does not work on process start

## DigiWF Engine

- Added element templates to create presigned urls and send emails
- Created a small demo process that
  -  shows the s3 specific process config
  -  creates presigned urls for all files in a *test* directory
  -  sends a mail with the files from the *test* directory attached
- Process Config
  - Save process config as instance variable when starting a process
  - Added a tasklistener that adds the s3 config as an input parameter to every task
  - As fallback use the s3 configs saved in application.properties (default s3 config)
- Save s3 config for sync (http Endpoint for multifile input) and async usage (kafka topic)
- Refactoring to reduce code

## S3 Service

- Added asyncapi to the s3 integration service to create presigned urls
- S3 integration service will create presigned urls for all files in the specified path
- Presigned urls are sent as correlate message event back to the engine
- Refactored logic to create presigned urls to simplify it
- Created an element template for creating presigned urls (digiwf-engine repo)

## Email Integration

- Pass file attachments as input parameter to email integration service
- Email Integration Service will download files from presigned urls and attaches them to an email before sending it
- Refactored validation using javax validation. Added validation rule that presigned urls must use the GET action. All other actions don't make sense in this context.
- Refactored email element template
