### ISSUE TITLE
Extend streaming process template

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#274]
## Description

We need to extend the streaming process template to be able to throw BPMN errors for the processes using the functionality as Call Activities.
[](url)![F3E075C5-DB2E-42AA-90ED-4D90B52C174D.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/0b4e8cd2-3749-4dc8-9941-17b9698101d9)

## Details
- Add the event subprocess with the message `bpmnError` this message name should be used in the bpmn error consumer when correlation the error event
- check on the path if the variable app_bpmn_erorrs_enabled is set, only proceed to the error end event if the variable is available and true
- call the implemented incident logic from the incident consumer if the variable is not set
- Configure the error end event to have a dynamic error code and error message that is bind to the variables set within the bpmn error consumer when correlation the bpmnError message
- Create a process test for the template
  - within a process and attached error events
  - with and without the app_bpmn_errors_enabled variable set

**Comment by martind260** [comment]
@dominikhorn93 Calling the implemented incident logic means propagate the message to the Generic DLQ for incidents (from here: https://app.zenhub.com/workspace/o/it-at-m/digiwf-project/issues/147)

**Comment by dominikhorn93** [comment]
This is one option.
But I would prefer to do it via External Task Worker, otherwise we would send messages to ourselves.

**Comment by martind260** [comment]
Throwing a dynamic error code from an error event is not possible. Instead we use a delegate to throw the dynamic error.
