### ISSUE TITLE
[feature] [feature] Upgrade to Vue2.7 +Vite

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#277]
**Is your feature request related to a problem? Please describe.**
As stated in https://blog.vuejs.org/posts/vue-2-7-naruto.html, version 2.7 of vue is the final minor and Vue 2 will reach its End of Life by the end of 2023.

To prepare the switch to vue3 it is recommended by RefArch to first upgrade vue to the final minor and include Vite.

**Describe the solution you'd like**
Vue is upgraded to version 2.7 and Vite is included

**Describe alternatives you've considered**
Big bang to Vue3

**Additional context**

**Comment by darenegade** [comment]
Already done: https://github.com/it-at-m/digiwf-core/commit/4e15f32ed15576ba9d36b26a81a932248a46d951
