### ISSUE TITLE
[bug] favicon.ico is only suitable for the arbeitgeberinmarke

### ISSUE THREAD

**Issue by klml** [it-at-m/digiwf-project#283]
**Describe the bug**

![](https://digiwf.muenchendigital.io/favicon.ico)

https://github.com/it-at-m/digiwf-project/blob/main/static/favicon.ico is only suitable for the [arbeitgeberinmarke](https://stadt.muenchen.de/infos/karriere-arbeitgeberinmarke.html)

I suggest to use default www.muenchen.de

![](https://www.muenchen.de/media/css/images/fav/favicon.ico)

Do you want a PR?

**Comment by xdoo** [comment]
Thank your bug ticket @klml 

I think we should stay with yellow. Perhaps something like that :P

![image](https://user-images.githubusercontent.com/712911/178288253-105a0778-c1e1-4071-8397-be88953e9d66.png)

**Comment by klml** [comment]
@xdoo that is even better, I love penguins. thx

**Comment by xdoo** [comment]
![image](https://user-images.githubusercontent.com/712911/180748567-6ae647b4-ffe3-43f8-b33d-77109d2c976c.png)
