### ISSUE TITLE
Creation of a project page for all associated repositories

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#29]
**Is your feature request related to a problem? Please describe.**
At the moment it is obvious by the prefix of a repository which projects belong to DigiWF. With growing numbers, however, this becomes increasingly confusing. There are also other OpenSource projects that are used in the context of DigiWF

**Describe the solution you'd like**
We need a project page where all repositories are linked. With a short description what it is about. Maybe we can include a kind of GitHub Card, where the description is loaded from GitHub.

**Comment by dominikhorn93** [comment]
@xdoo created a repository for that

**Comment by xdoo** [comment]
Yes. I think the modules section is the right place. 

What do you think?

- One file per project
- One file per DigiWF module (Core, Integration, Tasklist, Co-Creation)
- One file for all?

![image](https://user-images.githubusercontent.com/712911/155326221-073eda5e-5215-4f8a-8123-c8a1ffd1acb7.png)

**Comment by xdoo** [comment]
I'll do it with one file per module :)
