### ISSUE TITLE
Register client application at COSMOS

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#311]
## TODO
- The client application (here the integration artifact) has to be registered at OCE COSMOS. 

see [https://app.zenhub.com/files/459665365/a3700b61-a87f-4d2e-b8ec-78504497cf9d/download](https://app.zenhub.com/files/459665365/a3700b61-a87f-4d2e-b8ec-78504497cf9d/download)

## Criteria
- The COSMOS installation can be reached by the client.

**Comment by darenegade** [comment]
Successfully tested the connection between the integration artifact and oce-cosmos
