### ISSUE TITLE
Uploadable BusinessContext for CIT forms

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#317]
As a process designer I want to be able to connect new forms provided by the CIT form server without reconfiguring and restarting the formserver-integration

* Extend co-creation platform to accept business context json as new resource type.
* Extend formserver-integration to not[ read business context configuration](https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/tree/develop/digiwf-formserver-integration-core/src/main/java/de/muenchen/fktemplate/digiwf/businesscontext) from a prop file but from DB

**Comment by darenegade** [comment]
Will be solved with digiwf-core#271
