### ISSUE TITLE
As a user I want to create and reuse my own search filters

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#339]
## Description

Often, the same criteria must be searched for. At the moment, there is only a full text search in DigiWF. It would be helpful for users to be able to save the search entries in a filter. This would make it easier to filter on specific character strings.

## Tasks
- Implement Filter Domain ( id, filterString, userId, pageId)
- Add possibility to add / delete / use filters in the tasklist
- Visualize how many tasks match per filter in a badge
- Autocomplete box for choosing a filter

**Comment by martind260** [comment]
@dominikhorn93 Wollen wir daraus einen eigenen Microservice machen oder in die Engine integrieren?
