### ISSUE TITLE
As a user, I want my current page number in the task list not to be lost when I change pages

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#341]
## Description

When starting on a certain page in task editing, one often wants to edit the tasks on the same page one after the other. However, the position is not saved in the frontend store. That is why you always end up on the first page when you navigate to the list. The position should be stored separately in the frontend for each task list.

## Tasks

- Create a store for saving page positions
- Store and load the position for process instances, tasks, group tasks, group tasks in work, processes

**Comment by lmoesle** [comment]
Note: In another epic we implement pagination and fulltext search in the backend. Therfore, it would be useful to store the page information in url parameters to prepare the tasklist for https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/375

**Comment by darenegade** [comment]
@dominikhorn93 How much SP are left here?

**Comment by dominikhorn93** [comment]
40% is done I guess.

**Comment by dominikhorn93** [comment]
@StephanStrehlerCGI can you pick this up when implementing the pagination?
