### ISSUE TITLE
Documentation for Error Handling DigiWF Connector V2

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#363]
We need documentation for error handling (How can an integration artifact send an error back to the process?) via the DigiWF Connector V2.

The right place would be: https://digiwf.muenchendigital.io/resources/documentation/concept/integration

**Comment by darenegade** [comment]
blocked by #394

**Comment by darenegade** [comment]
https://github.com/it-at-m/digiwf-core/pull/84
