### ISSUE TITLE
Improve tasklist performance

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#366]
**Is your feature request related to a problem? Please describe.**

The digiwf tasklist loads all user/group tasks assigned to the user at once. If a user has multiple hundred or thousand tasks assigned, it takes a while for the tasklist to load all tasks from the api.

**Describe the solution you'd like**

We should refactore the frontend and the task api to not load all tasks at once. Maybe we use api pagination (backend) or another concept to reduce the amount of data.

**Describe alternatives you've considered**

Alternatively, we could move to a more real time functionality by using websockets and/or graphql to stream the task data to the frontend.

**Additional context**

Loadtest results: https://git.muenchen.de/digitalisierung/digiwf-load-test/-/pipelines/125870

**Priority**

Go live of parkausweis managment is in november. Therefore, it would be great if we could fix this issue advance.

**Comment by lmoesle** [comment]
**Solution**

- Pagination in the backend
- Frontend sends Page Information to the backend
- We can use Spring Paging und Sorting
- Additional API Endpoints für Paginated Search of User Tasks and Group Tasks
- We stick with a paginated table in the frontend. We don't use infinity scroll

**Comment by lmoesle** [comment]
**Tasks**

- Save Page Information in the URL (Issue https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/341)
- Paginated Backend Controller for Taskinfo Entities (User Tasks) - Authorization
- Paginated Backend Controller for Taskinfo Entities (Group Tasks)
- Implement Fulltextsearch in the Backend
- Fulltextsearch in the Frontend with Url Parameter that is sent to the backend

**Comment by darenegade** [comment]
Merged Epic with #338
