### ISSUE TITLE
Update repo docu

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#367]

**Comment by martind260** [comment]
![Repositories Ziel.drawio.png](https://images.zenhubusercontent.com/62274cd4c0d2a9dced8274e0/b8a9feea-38f9-4ca5-84fc-54d547bafb44)![Repositories Prod.drawio.png](https://images.zenhubusercontent.com/62274cd4c0d2a9dced8274e0/52780e5e-983b-4a5e-9ba6-c904eade0e41)

**Comment by dominikhorn93** [comment]
Super, vielen Dank für das Schaubild.
Ein paar kleinere Anmerkungen habe ich:
- Ich würde vuetify-jsonschema-form nicht auf Toplevel im Form-Builder oder der Tasklist sehen. Das ist einfache eine PeerDependency die notwendig ist durch den renderer und den builder
- Bpm Repo ist ext. aber OSS -> die Repos sind bei Miragon, aber öffentlich zugänglich -> https://github.com/FlowSquad/bpm-repo-client
- Teile des Bpm Server in der Co Creation sind OSS -> von Miragon -> https://github.com/FlowSquad/bpm-repo

**Comment by martind260** [comment]
>     * Ich würde vuetify-jsonschema-form nicht auf Toplevel im Form-Builder oder der Tasklist sehen. Das ist einfache eine PeerDependency die notwendig ist durch den renderer und den builder

Was ist mit digiwf-form-builder-settings, das ist auch auf Toplevel von Forms und im form-builder. Da auch raus?

**Comment by dominikhorn93** [comment]
> > ```
> > * Bpm Repo ist ext. aber OSS -> die Repos sind bei Miragon, aber öffentlich zugänglich -> https://github.com/FlowSquad/bpm-repo-client
> > 
> > * Teile des Bpm Server in der Co Creation sind OSS -> von Miragon -> https://github.com/FlowSquad/bpm-repo
> > ```
> 
> 
> Wir haben ganz viele 3rd party Libraries, die möchte ich nicht alle erwähnen. Ich möchte auch keine Werbung für Miragon machen ;-)

Das war nicht die Intention. Ich würde das aber wie oben rechts kennzeichnen -> da ist ja das `ext` Tag dran. 90% des Backends sind der Starter, der bei Miragon liegt. Du musst den nicht nennen oder rein schreiben. Würde das aber kennzeichnen, dass die LHM hier kein "Make" macht.
