### ISSUE TITLE
Store page information in url parameters

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#375]
Use the backend pagination endpoint in the frontend.

**Tasks**

* Store page information in url parameters
  * e.g. `?page=5&total=10`
* Send page information to the paginated backend api endpoint as GET request with url parameters

**Comment by StephanStrehlerCGI** [comment]
Was solved with issue https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/377
