### ISSUE TITLE
Init Documentation

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#395]
Add internal [digiwf-docs](https://git.muenchen.de/digitalisierung/digiwf-docs) to monorepo and build a pipeline to publish the documentation

acceptance criteria:

* base structure for documentation is in monorepo
* documentation is up and running

**Comment by lmoesle** [comment]
@darenegade soll die Doku weiterhin als Gitlab Pages veröffentlicht werden oder in Github?

**Comment by darenegade** [comment]
Die Doku sollte allen zugänglich sein, daher gehen wir zunächst auf GitHub pages.
Ich besorge aktuell eine eigene Domain unter muenchen.de. Vielleicht müssen wir dann nochmal was anpassen, aber das sehen wir dann
