### ISSUE TITLE
Integrate Modelling Handbook

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#396]
Convert the existing adoc handbook to markdown and integrate that into the central documentation: 
https://git.muenchen.de/digitalisierung/digitalwf-modellierungshandbuch

Mark LHM specific content and don't transfer that to the public docs. We need to find a different place for that

Maybe there is an converter from adoc to md. that needs to be found out

**aceptance criteria**
* Modellierungshandbuch steht auf https://digiwf.oss.muenchen.de/modeling/ zur Verfügung
* Alte, nicht mehr relevante Informationen, werden in einem separaten Issue dokumentiert, sodass es später erneuert werden kann
* Alte Infos als deprecated im bisherigen Handbuch markieren und nicht ins neue übernehmen

**Comment by dominikhorn93** [comment]
@darenegade should be done before adding example processes for the features

**Comment by LenaB34** [comment]
Formulardokumentation fließt in ein eigenes Ticket ein.
