### ISSUE TITLE
Integrate Platform Technical Documentation

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#397]
Most of the current technical documentation (without integrations) is already included. But there are some other sources we might need to look at.

* https://git.muenchen.de/digitalisierung/digitalwf/-/blob/master/docs/Technische%20Doku.adoc
* google drive Präsentations
* Readme's

Integrate No-LHM specific content
the other content needs to be discussed (maybe betriebshandbuch)

**Comment by darenegade** [comment]
@dominikhorn93 Kannst du die Inhalte bitte bereitstellen bzw. sagen, wo diese liegen

**Comment by dominikhorn93** [comment]
@darenegade um welche Inhalte geht es? Google Drive? Lass hier kurz dazu austauschen.

**Comment by darenegade** [comment]
Ja genau, du meintest, dass noch Sachen auf Google Drive liegen und du diese auf ein Netzlaufwerk verschieben willst

**Comment by darenegade** [comment]
Hier gab es bisher keine Bedarf, daher geschlossen
