### ISSUE TITLE
Code-Coverage einführen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#410]
Als Entwickler möchte ich die Code Coverage im PR sehen und ein Quality Gate bei 60-80% (new Code) dafür einrichten können.

* JaCoCo in Java/Maven
* Über CodeCov im PR sichtbar machen

**Comment by lmoesle** [comment]
Code Coverage mit Jacoco ist fertig -> https://github.com/it-at-m/digiwf-core/pull/85

**Comment by lmoesle** [comment]
Code Coverage reports mit Jacoco werden jetzt generiert, wenn man `mvn verify` ausführt. Um CodeCov einzurichten fehlen mir aber die Rechte in Github, da man ein Secret in Github hinterlegen sollten.

@darenegade, @dominikhorn93 kann bitte einer von euch beiden den CodeCov Part des Issues übernehmen? Die von Jacoco generierten Coverage Reports findet ihr unter `digiwf-coverage/target/coverage`

**Comment by darenegade** [comment]
Can do
