### ISSUE TITLE
Set up a development environment with one click

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#412]
Create a docker compose set up to start a development environment with just a few clicks/commands.

### Tasks

* Add infrastructure components to `stack/docker-compose.yml`
    * Kafka and Zookeeper for messaging (done)
    * Minio for S3 storage (done)
    * Mailhog for Email (done)
    * digiwf-gateway (done)
    * keycloak
    * postgres
* Add integration artifacts (with public docker containers) with custom profiles to enable/disable them on startup. 
     * Use docker image from [dockerhub](https://hub.docker.com/u/itatm)
     * Each integration should have its own profile
* Add the frontend (digiwf-task) list to the setup with a profile `tasklist` (done)
* Configure environments and `application.properties`
* Create documentation on how to setup the development environment (docker and non-docker)

### Criteria

* You can start the development environment with the command `docker compose up`
* You can start each integration service with an additional `docker compose up --profiles xxx`
* Dev setup is documented

**Comment by lmoesle** [comment]
Should we add a profiles switch to kafka, minio (s3), mailhog (email) too?

**Comment by darenegade** [comment]
[keycloak migration](https://github.com/mayope/keycloakmigration) für lokale autom. konfig

**Comment by darenegade** [comment]
Das Ticket aufspalten in PostgreSQL und Keycloak

**Comment by darenegade** [comment]
Already done

If something is missing we should create a new ticket with the specific thing to do
