### ISSUE TITLE
Migrate digiwf-asyncapi-docs to digiwf-core monorepo

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-project#413]
As a software developer I want to integrate the digiwf-asyncapi-docs into the digiwf-core monorepository to simplify maintenance and add the digiwf-asyncapi-docs starter to each application that uses spring cloud stream.

### Tasks

* Migrate digiwf-asyncapi-docs to digiwf-core
* Configure pom.xmls to integrate the digiwf-asyncapi-docs into the build mechanism
* pom.xml uses versions of shared packages from the parent (root pom in the digiwf-core)
* Archive old repository
* Refactoring to use the most recent version of spring-wolf
* Integrate the digiwf-asyncapi-docs to each application that uses spring cloud stream. It may also work to add the digiwf-asyncapi-docs starter to our spring-cloudstream utils

### Criteria

* Refactor the digiwf-asyncapi-docs and use the most recent version of spring-wolf
* digiwf-asyncapi-docs is integrated into the digiwf-core monorepo
* Old repository is archived
* Repository documentation is updated

**Comment by darenegade** [comment]
@lmoesle Brauchen wir das noch oder ist das nicht mit https://github.com/it-at-m/digiwf-core/pull/173 obsolet? (Wenn ja, bitte schließen)

**Comment by lmoesle** [comment]
@darenegade Nein, leider nicht. Wir haben eine eigene kleine Lib für Spring-Wolf gebaut, damit wir auch für die Async APIs eine automatisch generierte Doku haben.

Nachdem das Ticket schon etwas älter ist, schaue ich mir das Thema nochmal an und aktualisiere das Ticket ggf. nochmal.

**Comment by lmoesle** [comment]
Not needed anymore. Spring Wolf supports Spring Cloud Functions now and we could use it directly.
