### ISSUE TITLE
Dokumenten Upload funktioniert nicht mehr

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#416]
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/189
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/187

**Comment by darenegade** [comment]
Das hängt mit der Änderung #420 zusammen

Interner MR dazu: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/37

**Comment by darenegade** [comment]
"The property io.muenchendigital.digiwf.s3.client.defaultDocumentStorageUrl is not set."

**Comment by lmoesle** [comment]
Die Property `io.muenchendigital.digiwf.s3.client.documentStorageUrl` hat gefehlt. Ich hab die property in den Umgebungen hinzugefügt und so wie ich das testen könnte funktioniert der Dokumenten upload wieder.

**Comment by darenegade** [comment]
Wurde erledigt
