### ISSUE TITLE
Create sample processes

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#427]
As a DigiWF Developer i need some sample processes to smoke-test the engine and all the integrations to gain confidence in a release candidate.
Update Modelling-Handbook if needed

Out of scope: Legacy integrations

## acceptance criteria
* All sample process available on all environments (production only if restrictable access to digiwf admins)
* One Sample Process created with a large form and all possible inputs
   * requesting the process results in an group-task
   * summary of input as mail
* One Sample process created for each integration with all possible input parameters (depending on api)
* Up-to-date Modelling-Handbook

**Comment by dominikhorn93** [comment]
@martind260 where is the new WSDL?

**Comment by martind260** [comment]
@dominikhorn93 What do you need a WSDL for when creating sample processes?

**Comment by dominikhorn93** [comment]
Don't know how that happened.... was working on the DMS issue.
Found in in the inputmangement repo :)

**Comment by lmoesle** [comment]
Die Lasttest Prozesse können wir nutzen, um die Tasklist (Usertasks und Grouptasks) zu testen -> https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-engine/digiwf-engine-service/src/main/resources/prozesse/feature/loadtest
