### ISSUE TITLE
Release Sprint Dezember 1

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#433]
Tracking Issue

Comment all information necessary for production- and process-env of this sprint

**Comment by darenegade** [comment]
Remove S3: https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/426

**Comment by dominikhorn93** [comment]
Deploy digitalisierung-dms-eai before deploying the digiwf-engine-service

**Comment by darenegade** [comment]
https://wiki.muenchen.de/betriebshandbuch/index.php?title=Digital_WF/Release_Notes&sfr=betriebshandbuch&title=Digital_WF%2FRelease_Notes

**Comment by martind260** [comment]
redeploy bpm-modeler on digiwf-demo
