### ISSUE TITLE
Prozess lässt sich nicht starten, da Data-Validation fehlschlägt

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#434]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/200

**Comment by darenegade** [comment]
@lmoesle Ist das Thema fertig oder fehlt noch was?

**Comment by lmoesle** [comment]
Das Issue ist fertig. Ich hab vergessen, dass Ticket weiter zuschieben.

**Comment by darenegade** [comment]
@lmoesle Dann kannst du das interne Ticket auch auf Status::Erledigt setzen. Danke
