### ISSUE TITLE
Add process name to incident notifications

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#440]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/188

* Env: Umgebungsname (+ Farbe)
* Optionaler Vorschlag: Farbschema im Logo wird übernommen in Mail. D.h. IT@M Logo wird durch DigiWF Logo ausgetauscht und erhält Farb-schema, wie Applikation 
   * Bilder müssten in Openshift als Env oder andere Ressource eingebunden werden, damit digiWF-Core unabhängig bleibt
* Template für alle Mails (Incident, Aufgaben Zuweisung, usw.) anpassen: Text

**Comment by Sbivvds241** [comment]
das Laden der Grafik aus openshift wurde in ein zweites Issue ausgelagert.
https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/562
Im Rahmen dieses Issues wird nur die Anzeige des Prozessnamen im E-Mail umgesetzt.

**Comment by Sbivvds241** [comment]
https://github.com/it-at-m/digiwf-core/pull/279

**Comment by Sbivvds241** [comment]
process name is now shown in:
assignee notifiation
group task notification
incident notification
