### ISSUE TITLE
Text in markdown field is not displayed on following tabs

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#442]
## Description
Text in a markdown field is only displayed when the focus is on the field.
For example, by clicking in the field.

## Reproduce
* Call task with markdown field
* Enter text in markdown field
* complete task and pass to next task in priozess
* call new task
* no text appears in markdown (only on second or following tabs)
* if you click in the markdown field, the text appears

Note: the markdown is not located on the first stepper of the form

internal issues:
- https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/80
- https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/196

**Comment by StephanStrehlerCGI** [comment]
Bug konnte reproduziert werden: https://github.com/it-at-m/vuetify-jsonschema-form/blob/bugfix/442-markdown-text-is-not-visible/442-markdown-editor-bug-reproduction.html 
Dreckiger Workaround auf nativem JavaScript / HTML Basis konnte gefunden werden.
Bug liegt an easymde / codemirror. 

Bugfix mittels elegantem Weg so einfach nicht möglich. Vielmehr müssten wir codemirror bug fixen. 
@darenegade muss entscheiden, ob aufwendiger Bugfix sinnvoll ist.

**Comment by LenaB34** [comment]
Umsetzung & Darstellung noch unklar. Abstimmung mit Rene & Julia erfolgt für die Darstellung LHM. Schätzung aktuell nicht machbar, wird noch erfolgen

**Comment by darenegade** [comment]
@StephanStrehlerCGI Wo würden wir den "dreckigen" Fix einbauen?

VJSF macht uns immer wieder Probleme. Wir werden wohl langfristig wechseln müssen (#424). Daher würde ich die schnelle Lösung als Temp.-Lösung ins Auge fassen. Bin mir aber noch nicht sicher, wo wir das setzen des Values dann integrieren in der Lib.

**Comment by StephanStrehlerCGI** [comment]
Wir müssten in den vuetify tabs einen click listener einbauen und immer wenn dieser geklickt wird (also der Tab gewechselt wird) den Dom / das Schema durchgehen und schauen ob / wo wir EasyMDE haben. dann müssten wir von diesem den aktuellen Wert auslesen und wieder setzen.

**Comment by darenegade** [comment]
Braucht man wirklich einen Listener? Mir erscheint das nur nach einem Init-Problem. 

Wenn ich dein Beispiel so anpasse, dass ich das Element Ein-/Ausblende, dann besteht das Problem nur beim ersten Mal.


Bei den Tabs einen Listener zu bauen, der alle Markdown-Fields kennt oder findet, wäre nicht so toll.
Lass uns mal darüber reden.

**Comment by darenegade** [comment]
https://codepen.io/darenegade/pen/yLRbjGK

**Comment by darenegade** [comment]
@StephanStrehlerCGI @lehju 

Hiermit konnte ich das Problem lösen:

![image](https://user-images.githubusercontent.com/10849776/234605656-3cf89d7c-0a88-4031-92ec-f8b45948e630.png)

Siehe [CodePen](https://codepen.io/darenegade/pen/yLRbjGK)

Könnt ihr das verifizieren?

**Comment by StephanStrehlerCGI** [comment]
@darenegade 

Mach ich. ich bilde mir ein, dass schon probiert zu haben. aber dein beispiel funktioniert ja. ich schaue es mir gleich mal an

**Comment by darenegade** [comment]
Abstimmung zwischen @dominikhorn93 und @StephanStrehlerCGI notwendig für release der Änderung
