### ISSUE TITLE
Abgleich Demo - Processes-Test / Prod - Processes-Demo

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#452]
**Is your feature request related to a problem? Please describe.**
Stabile Umgebungen für die Prozessdesigner

**Describe the solution you'd like**
Processes-Test & Processes-Demo sollte exakt gleich zu Prod sein

Dies betrifft die grundlegenden Konfigurationen soweit möglich.
Einzig die Anbindungen an Drittsysteme in der Processes-Demo sind weiterhin auf möglichst stabile Testsysteme

**Additional context**
optimize und Elasticsearch wird hier nicht behandelt (#447)

**Acceptance criteria**
* Processes-Test = Prod
* Processes-Demo = Prod

- [x] Abgleich DigiWF-OPs
- [ ] Secrets korrekt überführt
- [x] Topics einrichten lassen

**Priority**
When is the feature needed

**Comment by darenegade** [comment]
![DigiWF-Umgebungen.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/51f14d46-4ef0-4a20-bb6f-f68b1288ee80)

**Comment by martind260** [comment]
ElasticSearch ordered: REQ0412826
Topics ordered: #123
