### ISSUE TITLE
Create new Env: HotFix

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#454]
We need a new Env called ~~Early Access &~~ HotFix. 

~~Early Access: With this env process-designer can test new digiwf features before release~~
HotFix: With this env process-designer can reproduce Bugs in Production without destroying the Test/Demo-Environment

https://git.muenchen.de/digitalisierung/digiwf-ops#umgebungen-und-deren-zusammenhang

Features: 
~~State of Early-Access is equal to Demo, but without Optimize.~~ -> Demo is used for that purpose
State of HotFix ist equal to processes-demo, but without optimize

Name:

HotFix: `digiwf-processeshotfix`

Needs new Databases and Kafka-Topics

Internal Tickets:
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/259

**Comment by LenaB34** [comment]
Die Frage ist, ob eine weitere Umgebung benötigt wird? @darenegade 
-> Prozesses Early Access wird die neue Umgebung genannt.
-> Early Access wird erst mal nicht erstellt, hierfür wird unsere Demo genutzt.
-> HotFix muss erstellt werden.

**Comment by simonhir** [comment]
Interner MR für Openshift-Projekt:
https://git.muenchen.de/openshift/projects/-/merge_requests/356

**Comment by simonhir** [comment]
Service-Now-Ticket für neuen S3-Bucket: REQ0479036

**Comment by simonhir** [comment]
Interner MR für Cocreation Deployment: https://git.muenchen.de/digitalisierung/bpm-server/-/merge_requests/38

**Comment by darenegade** [comment]
@simonhir Hab die Story auf Done verschoben, wie im Daily besprochen
