### ISSUE TITLE
Release Sprint Januar 1

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#467]

**Comment by darenegade** [comment]
Ressourcen wurden verändert, daher müssen alle Services neu deployed werden auf Processe-* / Demo / Prod

Siehe
* https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/52
* https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/52

**Comment by darenegade** [comment]
Es stehen nun genügend Ressourcen zur Verfügung, sodass alle Services in Prod 2-Fach skaliert werden können

Siehe:
* https://git.muenchen.de/openshift/openshift-configs/-/issues/2673

PS: Gateway-Config wurde angepasst, sodass Hazelcast funktioniert und auch das Gateway 2-fach skaliert werden kann

**Comment by darenegade** [comment]
Frontend in Version 21.2 release bauen und ausbringen

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/216#note_540680

**Comment by darenegade** [comment]
Camunda-Connector und Formserver-Integration muss noch in Prod deployed werden. Dies ist eine Konsquenz aus dem Abgleich Processes-* & Prod:

https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/452

MR in Digiwf-Ops fehlt noch

**Comment by Sbivvds241** [comment]
Anpassungen für Parkraum.Test auf Processestest-Umgebung:
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/57

**Comment by Sbivvds241** [comment]
Umstellung auf neuen DMS Endpoint

**Comment by Sbivvds241** [comment]
2-Fach-Skalierung der Pods in Umgebungen Demo, Processes-Demo, Processes-Test und Prod
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/59

**Comment by Sbivvds241** [comment]
Incident notification om Processes-Demo, Processes-Test und Prod
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/60
