### ISSUE TITLE
Lange Texte (z.B. JSON > 2000 Zeichen) im Formular darstellen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#469]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/111

**Comment by darenegade** [comment]
@dominikhorn93 Gibt es hier eine Begrenzung von Camunda, die wir einhalten müssen, oder können wir beispielsweise auf 10k erhöhen?

**Comment by dominikhorn93** [comment]
Die Standardgrößen der Spalten sind 2K.
Alternativ kann man als byte array serialisieren.
Weiß nicht genau wie wir damit umgehen sollen... erhöhen verschiebt das Problem nur. Und man müsste verschiedenste Spalten anpassen. Ich denke wir sollten überlegen ob wir das nicht gleich richtig angehen.

@zambrovski was meinst du dazu?

**Comment by darenegade** [comment]
> Die Standardgrößen der Spalten sind 2K

Und davon sollte man nicht abweichen? Warum nicht?

> erhöhen verschiebt das Problem nur

Von welchem Problem sprichst du hier?

> Ich denke wir sollten überlegen ob wir das nicht gleich richtig angehen.

Was wäre den aus deiner Sicht richtig?

**Comment by dominikhorn93** [comment]
> > Die Standardgrößen der Spalten sind 2K
> 
> Und davon sollte man nicht abweichen? Warum nicht?

Hat Auswirkungen auf mehrere Spalten auch in der Historie von Camunda. "Einfache" Variablen werden anders behandelt als byte Arrays. Hier kann @zambrovski aber mehr dazu sagen.

> > erhöhen verschiebt das Problem nur
> 
> Von welchem Problem sprichst du hier?

Heute sind es 10K morgen 20K.

> > Ich denke wir sollten überlegen ob wir das nicht gleich richtig angehen.
> 
> Was wäre den aus deiner Sicht richtig?

Wir sollten die Werte entweder extern speichern und eine Referenz dazu in der Engine oder bspw. Textareas von Anfang an als byte array serialisieren.

**Comment by darenegade** [comment]
>Heute sind es 10K morgen 20K.

Irgendein Limit muss man aber immer setzen, und es agil zu erhöhen, wenn der Bedarf da ist, klingt jetzt für mich nicht widersprüchlich, solange wir das nicht ständig machen. Die Frage ist, welches Limit sinnvoll ist. Bei unseren internen Apps haben wir immer etwas zwischen 1 - 10k bei Textareas. Max von der DB wäre eh 64k, aber das ist schon sehr viel. 10k an sich ist auch schon viel und falls das mal nicht ausreicht, kann man wirklich die Sinnhaftigkeit der Speicherung solcher Romane innerhalb von DigiWF bei den Kunden hinterfragen. 

> Wir sollten die Werte entweder extern speichern und eine Referenz dazu in der Engine oder bspw. Textareas von Anfang an als byte array serialisieren.

Auch hier wäre aber ein sinnvolles Limit notwendig. Insgesamt klingt das für mich aber nach etwas zu viel des Guten. Wir wollen ja kein Word nachbauen. Über das ByteArray können wir diskutieren, falls das bei Camunda Vorteile hat und das nicht zu viel Aufwand im Handling hintenrum erfordert

**Comment by dominikhorn93** [comment]
> > Heute sind es 10K morgen 20K.
> 
> Irgendein Limit muss man aber immer setzen, und es agil zu erhöhen, wenn der Bedarf da ist, klingt jetzt für mich nicht widersprüchlich, solange wir das nicht ständig machen. Die Frage ist, welches Limit sinnvoll ist. Bei unseren internen Apps haben wir immer etwas zwischen 1 - 10k bei Textareas. Max von der DB wäre eh 64k, aber das ist schon sehr viel. 10k an sich ist auch schon viel und falls das mal nicht ausreicht, kann man wirklich die Sinnhaftigkeit der Speicherung solcher Romane innerhalb von DigiWF bei den Kunden hinterfragen.

Wenn wir das auf 10K erhöhen hat das auf jedenfall Auswirkungen an unterschiedlichen Stellen.
Dazu würde ich den Support von Camunda kontaktieren (wir haben hier ja Consulting mit im Vertrag) und nochmals nachfragen was hier bedacht werden muss.

> > Wir sollten die Werte entweder extern speichern und eine Referenz dazu in der Engine oder bspw. Textareas von Anfang an als byte array serialisieren.
> 
> Auch hier wäre aber ein sinnvolles Limit notwendig. Insgesamt klingt das für mich aber nach etwas zu viel des Guten. Wir wollen ja kein Word nachbauen. Über das ByteArray können wir diskutieren, falls das bei Camunda Vorteile hat und das nicht zu viel Aufwand im Handling hintenrum erfordert

Das war nur ein möglicher Ausweg, auf eine Erhöhung verzichten zu können. Aber ich würde da auch wirklich nochmal @zambrovski fragen, was er davon hält. Er hat da etwas mehr Erfahrung wenn es um die DB von Camunda 7 geht.

**Comment by darenegade** [comment]
FYI: Thema ist aus fachlicher Seite doch nicht mehr so relevant. Aber ich würde die Diskussion hier gerne noch beenden, da es eventuell wieder aufkommt.

Ob wir es dann umsetzen, können wir dann entscheiden.

**Comment by zambrovski** [comment]
Rein technisch gibt es dort verschiedene Möglichkeiten.

**Comment by darenegade** [comment]
Anforderung kam nicht mehr auf und daher wird Ticket geschlossen
