### ISSUE TITLE
Dokumenten-Feld nur in Größe 12 anschaulich

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#470]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/157

**Comment by LenaB34** [comment]
Keine hohe Prio - Wird auf Ready zurückgeschoben

**Comment by dominikhorn93** [comment]
Die Library kann das leider nicht.
Man kann den Titel "fIles" verstecken, es landet aber immer in 2 Reihen, da bei verschiedenen Objekte (durch properties gegeben) ein Umbruch gemacht wird.

**Comment by lmoesle** [comment]
@dominikhorn93 kannst du die Info bitte auch noch ins Modellierungshandbuch aufnehmen? Für die User ist das glaube ich ganz gut zu wissen, dass custom fields (wie das file input) immer die volle Breite verwenden.

**Comment by LenaB34** [comment]
Thema fließt in die Formulardokumentation ein.

**Comment by darenegade** [comment]
Die Doku dazu fehlt immernoch
