### ISSUE TITLE
Reiseantrag (PROD): Dokumenten Upload "Das Dokument konnte nicht hochgeladen werden."

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#471]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/222

**Comment by StephanStrehlerCGI** [comment]
Laut Gitlab sollte das durch 
https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/514
 behoben werden.

**Comment by darenegade** [comment]
@StephanStrehlerCGI @lehju Das ist dann nicht mehr blocked, oder?

https://github.com/it-at-m/digiwf-core/pull/194

**Comment by darenegade** [comment]
Funktion wurde umgesetzt und muss nun final überprüft werden, ob dies es erledigt hat.
Mit dem nächsten Release steht es dann den Usern zur Verfügung
