### ISSUE TITLE
Darstellung der Formulare in Aktuelle Vorgänge teilweise fehlerhaft

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#472]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/171

**Comment by dominikhorn93** [comment]
Fehler kann nicht reproduziert werden. Vermutlich mit einer Änderungen am Benutzerinput bereits erledigt. Review wird durch HR Portal gemacht.

**Comment by dominikhorn93** [comment]
Liegt an der Objektliste. Hier müssen CSS Klassen angepasst werden
