### ISSUE TITLE
Reiseantrag (PROCESSESTEST): Aufgabenanzeige funktioniert nicht

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#479]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/227

**Comment by dominikhorn93** [comment]
Ich glaube da fehlen nur Berechtigungen im Cockpit. Ich schau mir das an

**Comment by dominikhorn93** [comment]
Die Einstellung hat gefehlt: 
![image.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/85b90249-8dfe-46b6-bead-355c60d7d71c)

@a-m-zill @Sbivvds241 wo wollen wir das für den Umgebungssetup festhalten?
Sollten wir dafür nicht eigentlich ein SQL Init Skript haben, dass so etwas nicht vergessen wird?
