### ISSUE TITLE
Datumeingabe zusätzlich auch per Tastatur

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#487]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/123

Umsetzung muss noch diskutiert werden, da dies aus der Lib kommt.

Alternativen:
* Lib Input ändern
* Alternativen Date-Input bereitstellen

**Entscheidung:** Eigene Date-Input in Apps -> Package -> Components

Vorlage Date-Input: MAstER oder DigiWF-Legacy

Vorlage DigiWF-Custom-Input: [VMultiUserInput](https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-apps/packages/apps/digiwf-tasklist/src/components/schema/VMultiUserInput.vue)

Integration im Frontend: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-apps/packages/apps/digiwf-tasklist/src/components/schema/AppJsonRenderer.vue#L9

Transformation des JSON-Schema zur Laufzeit, sodass das Custom  `x-display` für Date Fields gesetzt wird und somit für alle vorhandenen Prozesse genutzt wird.

Form-Builder setzt bei Date autom. das `x-display`

Test auf Reiseantrag, da das Formular relativ komplex ist.

**Comment by StephanStrehlerCGI** [comment]
Für Transformator: Schema von Reiseantrag als Test nehmen.

**Comment by lehju** [comment]
Bearbeiterwechsel mit @StephanStrehlerCGI abgestimmt.
