### ISSUE TITLE
Umstellung der Process Apis auf Pagination

### ISSUE THREAD

**Issue by StephanStrehlerCGI** [it-at-m/digiwf-project#492]
### Ist Situation
Aktuell werden alle Prozesse als Liste vom Backend geholt und im Frontend nur in der UI Schicht auf Seiten aufgeteilt. Die gesamte Liste wird im Redux Store gespeichert. Dies kann zu Performanceproblemen führen.

### Soll Situation
Das Backend liefert die Ergebnisse Seitenweise an das Frontend aus. Dieses zeigt nur die entsprechenden Elemente an 

### Akzeptanzkriterien (Aufgabenbedingt technisch)
* Es gibt für die ServiceInstances und ServiceDefinition eine seitenbasierende API.
* Es muss möglich sein via Textsuche Elemente zu suchen
* Das Frontend speichert das Ergebnis nicht mehr im Redux Store ab sondern verwendet zum managen der Requests Tanstack Query.
* Die entsprechenden Komponenten wurden auf die Composition Api umgestellt.
* Im Menü wird weiterhin die Anzahl der aktuellen Vorgänge angezeigt.

### offene Punkte

Wording Problem: Im Frontend heißt das alles processDefinition und processInstances. Im Backend wird aber Service verwendet. Welche Bezeichnung ist richtig?

### technische Hinweise

Die beiden benötigen Rest Controller:
ServiceInstanceController: io.muenchendigital.digiwf.service.instance.api.resource.ServiceInstanceController
ServiceDefinitionController: io.muenchendigital.digiwf.service.definition.api.resource.ServiceDefinitionController

Für Tanstack Query kann die Umsetzung der Tasks als Vorlage genommen werden.

**Comment by darenegade** [comment]
Aktuell haben wir in der UI auch das Problem, dass nur 10 Elemente angezeigt werden, obwohl mehr vom Backend kommen. Liegt daran, dass die PagableList schon verwendet wird und Default-Size auf 10 steht, aber kein Footer existiert zum weiterschalten der Page

**Comment by dominikhorn93** [comment]
Wegen Polyflow nach hinten geschoben
