### ISSUE TITLE
Entfernen von VueX aus Frontend

### ISSUE THREAD

**Issue by StephanStrehlerCGI** [it-at-m/digiwf-project#493]
### Ist Situation
Aktuell wird VueX als Caching Layer im Frontend verwendet. Die Validierung des Caches muss durch den Entwickler behandelt werden.

### Ziel Situation
Es wird Tanstack Query via Composition Api verwendet um besser Mutations zu handhaben.

### Akzeptanzkritieren

* Die Redux Logik wurde ersetzt
* Vuex als Dependency wurde entfernt
* Alle als Deprecated markierte Funktionen in persistentFilter.ts wurden entfernt.

**Comment by darenegade** [comment]
Wir müssen wohl VueX behalten

https://github.com/it-at-m/digiwf-core/issues/288
