### ISSUE TITLE
Release 2 Januar

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#496]

**Comment by dominikhorn93** [comment]
Camunda Cockpit updaten
- in Gitlab Tag / Release bauen
- git-ops repo anpassen

**Comment by lmoesle** [comment]
Tasklist und Engine updaten für die Pagination

**Comment by lmoesle** [comment]
> Camunda Cockpit updaten

Beim Camunda Cockpit schlägt die build Pipeline fehl. Deswegen haben wir das Cockpit nicht aktualisiert

**Comment by lmoesle** [comment]
Wir haben die Engine und Tasklist erfolgreich released.

**Comment by Sbivvds241** [comment]
Hab den camunda connector jetzt erstmal auf 0 gescaled, 
weil immer dieser Timeout kommt und er sonst immer wieder versucht neu zu starten
