### ISSUE TITLE
Reiseantrag (PROD): org.springframework.orm.jpa.JpaSystemException: could not execute statement [...]

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#500]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/230

**Comment by darenegade** [comment]
Erhöhung von folg. Columns auf 2k notwendig:

https://github.com/it-at-m/digiwf-core/blob/1c4ca8303ae95c8cf4ddc3e529906ea0d2a53fa2/digiwf-engine/digiwf-engine-service/src/main/resources/db/migration/V7__ProcessInstanceInfo.sql#L7

https://github.com/it-at-m/digiwf-core/blob/1c4ca8303ae95c8cf4ddc3e529906ea0d2a53fa2/digiwf-engine/digiwf-engine-service/src/main/resources/db/migration/V11__TaskInfo.sql#L4

**Comment by darenegade** [comment]
Es muss noch geprüft werden, ob diese beiden Tabellen ausreichen und ob dies Seiteneffekte haben kann bei der Nutzung der Spalten.

**Comment by darenegade** [comment]
@dominikhorn93 und @Sbivvds241 

Könnt ihr das Thema bitte gem. übernehmen. Danke

**Comment by dominikhorn93** [comment]
Würde das über Flyway lösen, sonst führt das auf einer "grünen" Wiese / neuen Umgebung zu Problemen -> https://github.com/it-at-m/digiwf-core/pull/101 

Würde vorschlagen auch die Task Info Description auf 2K zu setzen.
Ich teste die Skripte noch auf der Testumgebung -> sind ja idempotent, d.h. wir können es auch in P manuell ausführen

**Comment by dominikhorn93** [comment]
Die Description wird lediglich über https://github.com/it-at-m/digiwf-core/blob/4db92a5e1e0ed1e65793c5b4ed41cf9e13d930c4/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/service/instance/process/ProcessFunctions.java#L47 gesetzt. D.h. es hat keine anderen Auswirkungen
