### ISSUE TITLE
Autom. Version Bump after Release

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#501]
## Problem
Aktuell muss sowohl bei Apps, als auch Maven, nach dem Release die Version manuell hochgezählt werden.

## Lösung
Anpassung der Release Pipe, dass:
* Optionaler Parameter für neue Apps und Service Version
* Anpassung der Pipe, sodass die Version entsprechend angepasst und auf Dev commitet wird (Alternativ Auto PR)
* Wenn keine Version angegeben wir, dann autom. Hebung der Patch-Version
   * Bei Maven über [Version-Set](https://zteater.medium.com/automate-releases-to-maven-central-using-github-actions-a2bf1748b103)
   * Bei NPM mit Learna [Version](https://github.com/lerna/lerna/blob/main/commands/version/README.md) Befehl

**Comment by lmoesle** [comment]
Ich habe einen PR aufgemacht und das Ticket umgesetzt. Wir haben 2 unterschiedliche Versionen (apps und services), die man mit jeweils einem extra Feld angeben muss. Das hochzählen erfolgt dann jeweils getrennt, weswegen 2 Commits (apps und services) gemacht werden.

Das Ticket ist ein bisschen ein mindfuck, weil man es 2 unterschiedliche Versionen gibt und unsere Release Action ganz schön kompliziert ist.

Wenn wir für die apps und services dieselbe Version verwenden würden, dann könnten wir das Version hochzählen z.B. komplett über maven machen und von maven lerna triggern. Dann müssten wir jeweils nur einen Commit pro Release machen.
Wenn wir bei den beiden Versionen bleiben, dann sollten wir 2 Release Pipelines machen (jeweils ein .yml file für die apps und services). Dadurch würde die Pipeline einfacher und verständlicher werden. Das Risiko wäre auch deutlich minimiert, dass jemand beim Releasen die Versionen verwechselt.
@darenegade Wdyt?

**Comment by darenegade** [comment]
@lmoesle Ja können wir gerne so machen und die releases von Apps, Service & Docs in eigene Pipes stecken

Mittlerweile haben wir im CCSE auch eine neue Version einer Release-Pipe für Maven erstellt. Vielleicht können wir unsere damit noch etwas verbessern

Das hier ist die Beispielimplementierung: https://github.com/it-at-m/itm-java-codeformat/tree/main/.github

Hier die Doku dazu: https://git.muenchen.de/ccse/open-source-strategie-ccse/open-source-aktivitaeten/-/wikis/Maven-Central

**Comment by darenegade** [comment]
Wir können das gerne als eigene Story aufnehmen, falls die Pipe in der aktuellen Version Probleme macht oder beim nächsten Change der Pipe
