### ISSUE TITLE
Aufgaben werden nicht mehr einheitlich sortiert

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#515]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/232

Einheitliche Sortierung Backendseitig fehlt.

**Comment by StephanStrehlerCGI** [comment]
Wird mit der Umstellung der Prozess Api auf Pagination gemacht. https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/492
