### ISSUE TITLE
S3-Integration DMS

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#520]
Wir benötigen eine kurzfristige Möglichkeit auch Dokumente aus dem S3 in der E-Akte ablegen zu können. Dies wird im Rahmen von EOZF benötigt, wo der Prototyp bis Anfang März stehen soll.

Die Umstellung des DMS in digiwf-project#103 wird noch etwas Zeit in Anspruch nehmen, daher ist hier die Frage, ob wir einen Zwischen-Lösung bereitstellen können.

Interne Referenz: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/239

* Create und Update Delegate implementieren
* ElementTemplate anpassen

**Comment by darenegade** [comment]
Relevante Punkte im Legacy Code:

https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/dms/muc/process/createdokument/CreateDokumentDelegate.java#L41

https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/dms/muc/process/updateschriftstueck/UpdateSchriftstueckDelegate.java#L43

**Comment by lmoesle** [comment]
Element Templates sind gespeichert unter https://git.muenchen.de/digitalisierung/bpm-modeler/-/blob/develop/frontend/src/components/ElementTemplates.ts

**Comment by darenegade** [comment]
P10 wünscht sich hierfür einen früheren Release (Vor 05.03 - Ende Sprint)
Bitte abwägen, ob dies Sinn macht und wie hoch das Risiko ist. Wenn wir es vertreten können, dann mit P10 abstimmen. (Siehe Issue intern)

**Comment by LenaB34** [comment]
Thema muss zeitnah umgesetzte werden & in das nächste Release einfließen.

**Comment by dominikhorn93** [comment]
Templates:
[https://app.zenhub.com/files/459665365/65b3bb65-2bdb-442c-94b4-23f70e9723e3/download](https://app.zenhub.com/files/459665365/65b3bb65-2bdb-442c-94b4-23f70e9723e3/download)

[https://app.zenhub.com/files/459665365/259c9c46-cec3-4e70-841f-deef0cb0dd64/download](https://app.zenhub.com/files/459665365/259c9c46-cec3-4e70-841f-deef0cb0dd64/download)
