### ISSUE TITLE
Suche in Aufgabenliste findet Ergebnisse nur auf der ersten Seite

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#532]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/241

Wenn man in der Tasklist (z.B. Meine Aufgaben) auf die 2, 3, ... Seite navigiert, dann nach einer bestimmten Aufgabe sucht, wird keine Aufgabe gefunden. Siehe folgender Screenshot:

![Bildschirmfoto vom 2023-02-09 15-49-51.png](https://images.zenhubusercontent.com/622f4d4cf7a5f47ea3c5213c/184898f6-7d24-435c-bd34-f2c210fd19cb)

**Problem**

- Der User befindet sich im Frontend immer noch auf der dritten Seite, aber nach der Suche gibt es nur noch eine Seite
- Die Aufgabe wird angezeigt, wenn man zurück auf die erste Seite navigiert
- Im UI wird angezeigt *Seite 3 von 1*

**Gewünschter Zustand**

- Bei der Suche soll die aktuelle Seite auf Seite 1 zurückgesetzt werden
- Bzw. wenn ich nach einer Aufgabe suche sollen die Ergebnisse von Seite 1 angezeigt werden

**Comment by Sbivvds241** [comment]
Der Fehler kann in Testumgebung nicht nachgestellt werden, tritt aber in P auf.

**Comment by LenaB34** [comment]
Nachstellung in den verschiedenen Umgebungen.

**Comment by lmoesle** [comment]
Ich habe das Issue um ein paar nützliche Informationen ergänzt. Der Fehler kann lokal nachgestellt werden.

@Sbivvds241 du musst das nicht mehr in den Umgebungen testen.

**Comment by Sbivvds241** [comment]
Wenn man z.B. in Liste auf page 3 navigiert und nach Eintrag auf Seite 1 sucht,
wird zwar ein Ergebnis gefunden, aber der Anwender muss zuerst wieder auf Seite 1 zurückspringen,
um das Suchergebnis auch zu sehen

Tritt in Testumgebung genauso auf wie in P

**Comment by Sbivvds241** [comment]
gehört zu ServiceNow INC0296351
