### ISSUE TITLE
Behandeln von technischen und fachlichen Fehlern in den Integrationsbausteinen

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#534]
Ursprünglicher Bug Report: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/215

## Beschreibung

Wir müssen das neue  [Error Handling Konzept](https://github.com/it-at-m/digiwf-core/tree/dev/docs/src/integrations/error-handling) in den [Integrationen](https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-integrations) umsetzen.

**Zusätzliche Infos**

- Doku: https://github.com/it-at-m/digiwf-core/tree/dev/docs/src/integrations/error-handling
- Send BPMN Error: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-libs/digiwf-spring-cloudstream-utils/digiwf-spring-cloudstream-utils-core/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/bpmnerror/service/BpmnErrorService.java
- Send Incident: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-libs/digiwf-spring-cloudstream-utils/digiwf-spring-cloudstream-utils-core/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/incident/service/IncidentService.java

## Aufgaben in jeder  Integration

- Error Handling Implementieren
- Beispielprozesse anpassen / erstellen (StreamingTemplateV2 benutzen)
- Integration refactoren und die neue digiwf-message Lib verwenden

**Comment by Sbivvds241** [comment]
Eventuell gibt es hierzu schon ein Epic

**Comment by dominikhorn93** [comment]
- UseCases definieren
- Interfaces definieren
- Docs ergänzen
- bisherige Integration "refactoren"

**Comment by LenaB34** [comment]
Review muss noch erfolgen. Dokumentation muss noch erfolgen.

**Comment by lmoesle** [comment]
Priorität haben die S3, Cosys und Email Integration
