### ISSUE TITLE
adjust config-map for environment settings

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#551]

**Comment by lmoesle** [comment]
I adjusted the config maps for dev, test, demo and prod stages with these PRs:

- Processdemo and Processtest: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/84 

Additionally, I added a few more properties to the application.ymls to avoid topic autocreation

- https://github.com/it-at-m/digiwf-core/pull/206
