### ISSUE TITLE
Task-Service: Security (OAuth)

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#553]
Task-Service übernimmt alten DigiWF Client

Engine bekommt neuen Client und Task-Service kommuniziert per Service-Account mit Engine

**Comment by LenaB34** [comment]
Offene Fragen:
-  Bekommt die Engine eine neue Client für alle bestehende Benutzer?
-  Wie sind die LHM-Vorgaben für die Berechtigungsthematik?
-  Securitytests - Wie sind da die LHM-Wünsche?

**Comment by darenegade** [comment]
> Bekommt die Engine eine neue Client für alle bestehende Benutzer?

Die Engine bekommt einen neuen Client oder das Taskmanagement. Sollte im Kern egal sein. Die Benutzerverwaltung hängt nicht an diesen Clients

> Wie sind die LHM-Vorgaben für die Berechtigungsthematik?

In Bezug auf Tasks werden die Auths. über Gruppenzugehörigkeit im LDAP gelöst. Es erfolgen idR keine Rollen/Rechte im SSO. (Einzige Ausnahme ist Deploy-Rolle)

> Securitytests - Wie sind da die LHM-Wünsche?

Das können wir hier zunächst ausklammern

**Comment by LenaB34** [comment]
Wurde schon umgesetzt.
