### ISSUE TITLE
Task-Service: Schema-Validation + Task-Details

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#554]
Schema aus Engine holen via SchemaRef (Out-Port - Cached)
Validierung vor dem Complete

**Comment by LenaB34** [comment]
Offene Themen: 
- Unit-Tests / Integrationstests
- Cached

**Comment by darenegade** [comment]
> Unit-Tests / Integrationstests

Ja, analog dem ldap mit Wiremock

> Cached 

Ja, wobei wir über den Cache-Evict nochmal nachdenken müssen. Zu Not klammern wir das Thema aber auch erstmal aus

**Comment by LenaB34** [comment]
Unit-Tests/ Integrationstests umgesetzt. Cached noch offen & wird noch abgestimmt.
