### ISSUE TITLE
Anpassung Taskliste

### ISSUE THREAD

**Issue by zambrovski** [it-at-m/digiwf-project#556]
Neue API - Anpassungen auf den Taskservice müssen vorgenommen werden.
Umstellung kann in zwei Schritten erfolgen.
Tasklist wird für die Umstellung erstellt.

Akzeptanzkriterien:
- Darstellung aus der Engine wird wie die Tasklist überführt.
- Interne Frontend Bib für die Anbindung der Taskservice API

Offene Fragen:
- Filterthematik nach der ersten Umstellung?

**Comment by darenegade** [comment]
Wir benötigen hier vor dem Refinement noch eine Info, was sich an der API genau ändern wird

**Comment by darenegade** [comment]
Wir benötigen hier vor dem Refinement noch eine Info, was sich an der API genau ändern wird
