### ISSUE TITLE
TaskService: LDAP Anbindung

### ISSUE THREAD

**Issue by zambrovski** [it-at-m/digiwf-project#557]
Anbinden von LDAP, um an die LDAP Gruppen eines Users zu kommen. Dies kann über [EZ-LDAP](https://ezldap.muenchen.de/swagger-ui/index.html) erfolgen. Kopplung an EZ-LDAP muss diskutiert werden

Neben dem aktuellen Mock soll es eine neue Integration für EZ-LDAP geben

Aktuell:
https://github.com/it-at-m/digiwf-core/blob/5c1770752cf13320069ff8eb10b4db882cb89621/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/user/domain/service/LdapUserServiceImpl.java

Mock In Polyflow: 
https://github.com/it-at-m/digiwf-core/blob/feature/init_polyflow_task_management/digiwf-task/digiwf-tasklist-service/src/main/java/io/muenchendigital/digiwf/task/service/adapter/out/auth/group/MockUserGroupResolver.java

## Offene Fragen
* Fehlerbehandlung (Serviceunterbrechung, 404 von EZ-LDAP, usw) - siehe unten
* Test-URL von EZ-LDAP
* Nutzung Webclient oder Feignclient

## Akzeptanzkriterien
* Gruppen werden von EZ-LDAP geladen und für die Gruppentask-Zuordnung hergenommen
* EZ-LDAP Anbindung ist flexibel Austauschbar
* URLs konfigurierbar
* Webclient wird verwendet
* Fehlerbehandlung: Leere Menge an Gruppen
* Bei Fehlern eine Metrik führen

**Comment by LenaB34** [comment]
Termin in Planung für die Anbindung an LDAP (Vorgaben LHM, Konzeptionelle Richtung)

**Comment by lehju** [comment]
Das Thema Metrik wird in diesem Issue nicht bearbeitet. Wird eventuell mit AppDynamics umgesetzt.
