### ISSUE TITLE
Create a digiwf-cloud-stream-starter-utils

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#56]
In context of spring cloud stream, we need a little starter for:

- dynamic routing
- error handling
- ...

![Integrationskonzept für Services _ Feature Requests _ Ablaufdatum S3 (7).png](https://images.zenhubusercontent.com/6220c3e56c0bae718921783b/c31e1536-47a2-4b91-8a19-76c37c6dd634)

**Comment by xdoo** [comment]
@axd4  @dominikhorn93 can we close this?

**Comment by axd4** [comment]
@xdoo In my opinion, we can. Closed!
