### ISSUE TITLE
release Mai

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#564]
- [ ] Alle ToDos des Tickets hier abarbeiten
- [x] Release Candidate erstellen (aktuell Snapshot)
- [x] Manuelle Tests durchführen auf Test-Umgebung, soweit möglich
- [x] Release auf Demo (Alle Services releasen)
- [x] Restlichen Manuelle Tests durchführen auf Demo

**Comment by Sbivvds241** [comment]
Todo: Test-Release auf Demo-Umgebung:
Versionsnummern aller services aktualisieren

**Comment by Sbivvds241** [comment]
Todo: Ausführung der Test-Workflows auf DEMO-Umgebung

**Comment by simonhir** [comment]
TODO: HOTFIX auf Cocreation-Demo deployen

**Comment by simonhir** [comment]
TODO: S3-Integration
- Umbenanntes Secrect kopieren/verschieben
- Deployment für alten Service löschen

**Comment by simonhir** [comment]
TODO: Flyway Script digiwf-engine V21 wurde auf Test manuelle ausgeführt und wird beim nächsten Ausrollen auf der Test-Umgebung zu Fehlern führen. Hier muss nach Bauen und Deployment auf Test vermutlich die Tabelle `flyway_schema_histoy` angepasst werden. (Siehe #331)

**Comment by simonhir** [comment]
TODO: Test Cosys Integration

**Comment by lmoesle** [comment]
Für die EzLdap Story (https://github.com/it-at-m/digiwf-core/issues/342) habe ich eine Konfigurationsvariable im tasklist-service geändert. Der PR mit den Änderungen ist der hier -> https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/126

**Comment by darenegade** [comment]
Task-Service: Auf Process-* und später Prod muss die Task-Migration durchgeführt werden

**Comment by darenegade** [comment]
Das Cockpit hängt noch auf einer alten Version (7.14). Das wurde wohl vergessen hochzuziehen. Können wir dann auch gleich mitmachen und von 1.0 auf 1.14 heben

https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/141
