### ISSUE TITLE
Provide virus scan functionality

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#57]

**Comment by xdoo** [comment]
This should be solved in the S3 Implementation. In AWS S3 for example you have policies for that. 

See https://aws.amazon.com/de/premiumsupport/knowledge-center/s3-allow-certain-file-types/

**Comment by xdoo** [comment]
@dominikhorn93

**Comment by xdoo** [comment]
This is something for our FAQ section. See

**Comment by dominikhorn93** [comment]
@xdoo in my point of view we should ask the internal storage grid team...

**Comment by xdoo** [comment]
@dominikhorn93 how does this issue affect the DigiWF platform? As I've written above - the solution is part of the S3 implementation or the surrounding environment. 

I don't see a solution inside DigiWF - so I don't see a reason for reopening this ticket.

**Comment by dominikhorn93** [comment]
@xdoo sure this is nothing we can solve. But I would like to be able to provide information if someone asks us.
