### ISSUE TITLE
Functionality to restrict file extensions

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#58]

**Comment by xdoo** [comment]
You can restrict the file extensions on your S3 bucket via policy. This will not be provided by DigiWF.

If you'll use AWS see: https://aws.amazon.com/de/premiumsupport/knowledge-center/s3-allow-certain-file-types/

**Comment by xdoo** [comment]
@dominikhorn93

**Comment by xdoo** [comment]
This is something for our FAQ section. See #60

**Comment by dominikhorn93** [comment]
@xdoo if we configure a file input to only allow .pdf files than that should be checked... Maybe there is a feature in the presigned url generator?

**Comment by xdoo** [comment]
@dominikhorn93 

I don't see that. This is the fiel summary of "GetPresignedObjectUrlArgs":

![image](https://user-images.githubusercontent.com/712911/158350529-5aaa69e3-6e6f-482f-a595-bee477ffe851.png)

Anyway - what is the requirement?

- Restrict file extensions?
- Restrict file extensions for exact one way storing files in the bucket?

I think it should in most cases requirement 1 - I want exclusively pdfs in my bucket. So the solution must be a S3 functionality. I AWS this are policies. 

So I don't see a reason for reopening :smile:

**Comment by dominikhorn93** [comment]
So we have the following options:
- request file policies for storage grid bucket
- restrict file upload via Vue.js
