### ISSUE TITLE
Testinstanzen in Prod löschen

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#599]

**Comment by Sbivvds241** [comment]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/299

**Comment by dominikhorn93** [comment]
Wie wir bisher Instanzen bereinigen können:

- !!ACT_ Tabellen werden nicht angefasst!!
- Camunda Daten werden nur über das Cockpit gelöscht
- DWF_ Tabellen sind unsere und werden über die Datenbank gelöscht

**Comment by darenegade** [comment]
Termin hierzu am 30.06. - Bis dahin Blocked

**Comment by darenegade** [comment]
Lösungsmöglichkeiten wurden erarbeitet, benötigen aber noch etwas Rückenhalt und Infos. Mehr dazu nächste Woche

**Comment by darenegade** [comment]
@dominikhorn93 kannst du die Lösung zusammen im Pair mit @simonhir umsetzen? Dann bekommen wir das Thema auch endlich mal weg

**Comment by simonhir** [comment]
Ergebnis: Keine weiteren Schritte notwendig siehe internes Issue
