### ISSUE TITLE
Process Config für All-Input task anlegen

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-project#601]
siehe https://digiwf.oss.muenchen.de/modeling/processes/config/

Damit die Status Anzeige bei laufenden Tasks getestet werden kann muss bei mindestens einem der Example Prozesse (siehe TL3) eine Process Config implementiert werden.
siehe auch https://confluence.muenchen.de/display/MPdZ/Test-Dokumentation#TestDokumentation-TL-1:AnzeigevonVorg%C3%A4ngen

Hier soll für den All-Inputs Prozess eine Config mit zwei States erstellt werden. 
Prozess muss angepasst werden, damit der Status auch gesetzt/geändert wird.

Test-Doku in dem Zuge auch anpassen

**Comment by Sbivvds241** [comment]
siehe https://digiwf.oss.muenchen.de/modeling/processes/config/

Damit die Status Anzeige bei laufenden Tasks getestet werden kann muss bei mindestens einem der Example Prozesse (siehe TL3) eine Status Config implementiert werden.

**Comment by lmoesle** [comment]
Es muss eine Prozesskonfig für das Statusdokument angelegt und über die REST API der Engine deployed werden. Doku: https://digiwf.oss.muenchen.de/modeling/processes/config/
