### ISSUE TITLE
Rückbau Feature Toggle

### ISSUE THREAD

**Issue by StephanStrehlerCGI** [it-at-m/digiwf-project#631]
### Ist Situation
Aktuell ist der Feature Toggle für die meisten Netzwerkrequests eingebaut, obwohl die Engine Api abgeschaltet wurde. Damit gibt es unnötig viel Quellcode.

### Ziel Situation 
Der nicht mehr benötigte Quellcode ist ausgebaut und die Weiterentwicklung der Anwendung wird vereinfacht.

Dokumentation des Feature-Toggle Konzepts (Für zukünftige Feature-Toggles) 

#### Doku
- Prinzip von Feature-Toggle beschriebem
- Link auf PR / Issues

#### Engine Service
* Task RestController wurde entfernt
* Tests wurden angepasst

#### Api Gateway
* Die AddResponseHeader in den Default filters für das Setzen der Cookies wurden entfernt
* Im Ops Repo wurden die entsprechenden Environment Variablen nach Release entfernt

#### Digiwf-Engine-Api-Internal Api Client
* Client wurde neu generiert

#### Digiwf-tasklist Frontend
* Feature Toggle Button aus Navbar wurde entfernt
* Feature Toggle Logik wurde entfernt
* Task Middleware: Feature Toggle und Engine Service Calls  wurden entfernt
* Task Api Calls: Alle nicht mehr gebrauchten Engine Calls entfernen
* Task Mapper: Entfernen von Engine Task Mapper
* ~~Task Ladelogik umbauen, dass Userinformationen nachgeladen werden anstatt direkt mit dem Tasks geladen zu werden~~ -> Wird ausgelagert und nochmal in Ruhe diskutiert
  * Task Objekt im Frontend enthält nur userId als Information.
  * TaskItem wird umgebaut, dass eine Komponente zur Darstellung von Nutzernamen aufgerufen wird. Komponente bekommt UserId als Property und löst Namen über User Middleware selbst auf.
* Engine Rest Api Basepath Provider wurde aus Form entfernt
* Check ob VUserInput noch funktioniert

#### Digiwf multi file input
* Engine Rest Calls wurden ausgebaut

**Comment by lmoesle** [comment]
👍🏻 lgtm

Die einzige Frage, die sich mir stellt ist in welcher Story der Code im Multifile Input gelöscht wird. Aktuell arbeitet @StephanStrehlerCGI schon an [Tasklist: S3 Service sollte Methode PUT unterstützen](https://github.com/it-at-m/digiwf-core/issues/398) da wäre es evtl. einfacher gleich dort den Code zu löschen und den Punkt hier rauszunehmen.

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/631?planning-poker) with Zenhub @dominikhorn93 @simonhir @StephanStrehlerCGI @darenegade

**Comment by StephanStrehlerCGI** [comment]
Dokumentation ist schon vorhanden: 
https://digiwf.oss.muenchen.de/documentation/guides/taskservice-integration/#grundsatzlicher-aufbau

Ich ergänze noch die Links zu den Tasks

**Comment by darenegade** [comment]
Vielleicht den Link nicht auf Localhost zeigen lassen 🤣

**Comment by StephanStrehlerCGI** [comment]
doch. da gibt es immer den neuesten Scheiß. :-D (ist geändert)
