### ISSUE TITLE
Templating for new Repos

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#69]
We need a kind of templating for new repos. Keep it simple :)

- README
- logo
- license
- code of conduct
- docs
- issue templates
- ...

**Comment by a-m-zill** [comment]
@xdoo i have now created a template repo. Look here: https://github.com/it-at-m/digiwf-template
Further i have done a first test repo out of the template. Look here: https://github.com/it-at-m/test-repo-from-template.

I have added a small instraction section to the Readme. 

Please check, if this is for a first step enough or if you miss something.

**Comment by xdoo** [comment]
Thank you @a-m-zill :smile: 

It looks pretty good. One point:

![image](https://user-images.githubusercontent.com/712911/158361429-64784a2a-d5b9-4568-83da-4caebff8230c.png)

This is not a DigiWF OSS Template, but a generic template, that can be used for all repos in this github space. So the title should be changed, as well as the mail address and slack channel.

**Comment by xdoo** [comment]
Could you add this template to the space description? Perhaps with a short (or link to) description what to do?

![image](https://user-images.githubusercontent.com/712911/158361691-c893c090-b232-43f2-b601-958d58e14d0e.png)

**Comment by a-m-zill** [comment]
@xdoo , i think all your mentioned points are done. I have update the description of the template repo, because there was also DigiWF named. :) 
So i will close now this ticket.
