### ISSUE TITLE
Dependency checker in pipelines

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#70]
We need a dependency check in our pipelines to be 100% sure, that our main license will not be broken.

**Comment by xdoo** [comment]
could be a bot as well.

**Comment by xdoo** [comment]
https://github.com/marketplace/actions/ghascompliance

**Comment by a-m-zill** [comment]
https://github.com/marketplace/actions/license-approval

**Comment by a-m-zill** [comment]
**Short update**
I have added to three repositories a first version of a dependency checker.
Repos are:
- digiwf-form-builder
- digiwf-form-renderer
- digiwf-s3-integration
