### ISSUE TITLE
CIT Web Form Integration

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#71]
**As a process engineer I want to be able to generically start any process via a CIT Web Form**

## Description
We need an integration artifact to connect to the CIT Form Server.

![build-your-own-jms-integration-artifact.png](https://images.zenhubusercontent.com/6220c3e56c0bae718921783b/c71758e0-3b48-4ac5-9eee-c1b2e5d0ea68)

The CIT integration artifact should be able to 

- receive CIT Form submissions in ActiveMQ
- transform the CIT XML structure into JSON
- Upload files to S3
- Start process instances
- Configure relevant form-keys that should start processes

What is not part of this base artifact (`digiwf-cit-integration-starter`)?

- custom XML to JSON transformation: This should be done in the CIT space via XSLT. An alternative could be to create a custom CIT integration and transform it within that integration artifact.

#### Receive CIT Form submissions in ActiveMQ
User the CIT ActiveMQ starter to create a base project with the following structure:
- digiwf-cit-integration
- digiwf-cit-integration-starter
- digiwf-cit-integration-service
Setup the GitHub Action pipelines and use the oss template.

#### Transform the CIT XML structure into JSON
Use jackson to automaticaly map XML to JSON (StartInstanceTOV01)

#### Upload files to S3
upload files to a generated fileConext(UUID) and the corresponding Json Pointer.
The functionalty to indentify the correct Json Pointer path should be added to the digiwf-json-serialization starter.

#### Start process instances
Add a spring cloud stream function that can send a StartInstanceTOV01 to kafka. Add this functionality to the digiwf-cloud-stream-utils library.

#### Configure relevant form-keys that should start processes
Add the possibility to configure form keys via ENV varibales that can start processes.

#### Test setup for AMQ
Create a test setup for AMQ and the integration artifact that does no depend on the CIT form server.
User the parkausweismanagement XML structure for testing (first customer of that functionality)

**Comment by xdoo** [comment]
@Der-Alex-K fyi

**Comment by dominikhorn93** [comment]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/53

**Comment by dominikhorn93** [comment]
https://git.muenchen.de/mpdz/service-portal-eai-formserver/-/blob/main/src/test/resources/testdata/XML-Daten-Ferienpass.xml

**Comment by martind260** [comment]
CIT is just the enterprise offering the formserver as ONE of their products. So we should name the artifact formserver-integration to not get confused with other products we might integrate.

**Comment by martind260** [comment]
@dominikhorn93 Can you please add an issue for the test-starter project.

**Comment by dominikhorn93** [comment]
[https://app.zenhub.com/files/459665365![Bildschirmfoto 2022-09-01 um 10.56.57.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/a42141dd-f70d-4079-b7e3-a2dddbcdecbc)/7f050566-bbf8-4339-9d8a-6559a1ff201b/download](https://app.zenhub.com/files/459665365/7f050566-bbf8-4339-9d8a-6559a1ff201b/download)
