### ISSUE TITLE
 Implement autorization checks in the digiwf backend for handling files

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#72]
**Is your feature request related to a problem? Please describe.**
There is no authorization check when accessing files of a specific task field.

**Describe the solution you'd like**
Check if the user has access to the corresponding field key

**Comment by xdoo** [comment]
Where do you want to add those authorization checks? 

Is there are a picture, concept, description or anything like that, to show how authorization works on the platform?

**Comment by dominikhorn93** [comment]
Authorization comes with access to the task and the linked schema. The user has access to all data that is available in the schema (readonly possible)
![image](https://user-images.githubusercontent.com/27461050/158765212-b6ad4d5a-832a-481a-aec7-516c78f7339c.png)

**Comment by dominikhorn93** [comment]
@martind260 @xdoo wir müssen nochmal über den Prozessstart sprechen... Ich sehe hier ein Problem, da wir noch keine Daten haben in denen wir den S3 Pfad ablegen könnten.

**Comment by dominikhorn93** [comment]
@martind260 du verwendest bisher den fieldKey als Pfad -> das ist eine sehr gut Idee. Wie wäre es wenn wir den businessKey (fachlichen Kontext) davor schalten. Dann hätten wir das ganze Merging in die Datenstruktur nicht mehr. Wäre weitaus weniger komplex und wir prüfen nur ob die der fieldKey im Schema ist?
